In [5]:
import torch

In [9]:
randint = torch.randint(-100,100,(6,))
print(randint)

tensor([ 22,  73,  10,  99, -36,  64])


In [11]:
tensor = torch.tensor([[0.1, 1.2],[2.2, 3.1],[4.9, 5.2]])
print(tensor)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [15]:
zeros = torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
input = torch.ones(2,3)
print(input)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
